In [2]:
import pandas as pd
data = pd.read_csv('/home/kali/Downloads/Churn_Modelling.csv')
data.drop(['RowNumber','CustomerId','Surname'],inplace = True,axis = 1)
data.sample(30)
# data.Geography.unique()
data = pd.get_dummies(data,columns = ['Gender','Geography'])
x= data.drop('Exited',axis=1)
y = data.Exited
data.sample(5)
from sklearn.preprocessing import MinMaxScaler
scale = MinMaxScaler()
data[['CreditScore','EstimatedSalary' , 'Balance','Tenure','Age']]= scale.fit_transform(data[['CreditScore','EstimatedSalary' , 'Balance','Tenure','Age']])
data.shape


(10000, 14)

In [3]:
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
x,xt,y,yt = train_test_split(x,y)

model = tf.keras.Sequential()
model.add(keras.layers.Flatten(input_shape=(13,)))
model.add (keras.layers.Dense(10,activation = 'relu'))
model.add (keras.layers.Dense(5,activation = 'relu'))
model.add (keras.layers.Dense(2,activation = 'relu'))
model.add(keras.layers.Dense(1,activation = 'sigmoid'))
model.compile(optimizer = 'adam' , loss= 'categorical_crossentropy',metrics = 'accuracy')
model.fit(x,y,epochs = 10)
yt.shape
# xt.shape
x.shape

2022-10-16 16:11:03.719966: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-16 16:11:03.827050: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-10-16 16:11:03.829587: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-10-16 16:11:03.829599: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore 

Epoch 1/10


2022-10-16 16:11:04.773928: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-10-16 16:11:04.773944: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2022-10-16 16:11:04.773955: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (pyhacker): /proc/driver/nvidia/version does not exist
2022-10-16 16:11:04.774131: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


235/235 [==============================] - 1s 842us/step - loss: 0.0000e+00 - accuracy: 0.5035
Epoch 2/10
235/235 [==============================] - 0s 837us/step - loss: 0.0000e+00 - accuracy: 0.7945
Epoch 3/10
235/235 [==============================] - 0s 838us/step - loss: 0.0000e+00 - accuracy: 0.7961
Epoch 4/10
235/235 [==============================] - 0s 823us/step - loss: 0.0000e+00 - accuracy: 0.7965
Epoch 5/10
235/235 [==============================] - 0s 884us/step - loss: 0.0000e+00 - accuracy: 0.7964
Epoch 6/10
235/235 [==============================] - 0s 802us/step - loss: 0.0000e+00 - accuracy: 0.7964
Epoch 7/10
235/235 [==============================] - 0s 860us/step - loss: 0.0000e+00 - accuracy: 0.7964
Epoch 8/10
235/235 [==============================] - 0s 874us/step - loss: 0.0000e+00 - accuracy: 0.7964
Epoch 9/10
235/235 [==============================] - 0s 856us/step - loss: 0.0000e+00 - accuracy: 0.7964
Epoch 10/10
235/235 [==============================] - 0s

(7500, 13)

In [4]:
xt.shape

(2500, 13)

In [5]:
yt.shape

(2500,)

In [6]:
pred = model.predict(xt)
cm = tf.math.confusion_matrix(labels =yt, predictions =pred)
cm

79/79 [==============================] - 0s 569us/step


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1990,    0],
       [ 510,    0]], dtype=int32)>

In [7]:
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from acc_check import accuracy
# x,xt,y,yt = train_test_split(x,y)
# accuracy(x,xt,y,yt)

In [8]:
model= RandomForestClassifier()
model.fit(x,y)
pred = model.predict(xt)
# for i in pred:
#     print(i)
from collections import Counter
count = Counter()
count.update(Counter(pred))
count

Counter({0: 2188, 1: 312})

In [9]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(pred,yt)
cm


array([[1920,  268],
       [  70,  242]])

In [10]:
accuracy_score(pred,yt)

0.8648

oversampling

In [11]:

y.value_counts()

0    5973
1    1527
Name: Exited, dtype: int64

In [12]:
true , false = data.groupby('Exited')
true[1].Exited.value_counts(),false[1].Exited.value_counts()

(0    7963
 Name: Exited, dtype: int64,
 1    2037
 Name: Exited, dtype: int64)

In [13]:
import numpy as np

In [14]:
false = false[1].sample(7963,replace=True)
org_data = pd.concat([false, true[1]] )
x= org_data.drop('Exited',axis=1)
y = org_data.Exited

AttributeError: 'tuple' object has no attribute 'sample'

In [ ]:
x,xt,y,yt = train_test_split(x,y,test_size = .33 )
model = tf.keras.Sequential()
model.add(keras.layers.Flatten(input_shape=(13,)))
model.add (keras.layers.Dense(10,activation = 'relu'))
model.add (keras.layers.Dense(5,activation = 'relu'))
model.add (keras.layers.Dense(2,activation = 'relu'))
model.add(keras.layers.Dense(1,activation = 'sigmoid'))
model.compile(optimizer = 'adam' , loss= 'binary_crossentropy',metrics = 'accuracy')
model.fit(x,y,epochs = 10)
pred = model.predict(xt)


In [94]:
pred = np.round(pred)
accuracy_score(pred,yt)
confusion_matrix(pred,yt)

array([[1551,  522],
       [ 216, 1233]])

In [95]:
true , false = data.groupby('Exited')
sample = true[1].sample(2037)
org_data = pd.concat([sample,false[1]])
x= org_data.drop('Exited',axis=1)
y = org_data.Exited


Under Sampling

In [96]:
x,xt,y,yt = train_test_split(x,y,test_size = .33,stratify = y )
model = tf.keras.Sequential()
model.add(keras.layers.Flatten(input_shape=(13,)))
model.add (keras.layers.Dense(100,activation = 'relu'))
model.add (keras.layers.Dense(50,activation = 'relu'))
model.add (keras.layers.Dense(20,activation = 'relu'))
model.add(keras.layers.Dense(1,activation = 'sigmoid'))
model.compile(optimizer = 'adam' , loss= 'binary_crossentropy',metrics = 'accuracy')
model.fit(x,y,epochs = 10)
pred = model.predict(xt)

Epoch 1/10
86/86 [==============================] - 1s 1ms/step - loss: 0.6545 - accuracy: 0.6273
Epoch 2/10
86/86 [==============================] - 0s 1ms/step - loss: 0.5969 - accuracy: 0.6856
Epoch 3/10
86/86 [==============================] - 0s 1ms/step - loss: 0.5487 - accuracy: 0.7329
Epoch 4/10
86/86 [==============================] - 0s 1ms/step - loss: 0.5239 - accuracy: 0.7420
Epoch 5/10
86/86 [==============================] - 0s 1ms/step - loss: 0.5067 - accuracy: 0.7589
Epoch 6/10
86/86 [==============================] - 0s 1ms/step - loss: 0.4964 - accuracy: 0.7626
Epoch 7/10
86/86 [==============================] - 0s 987us/step - loss: 0.4882 - accuracy: 0.7732
Epoch 8/10
86/86 [==============================] - 0s 991us/step - loss: 0.4829 - accuracy: 0.7673
Epoch 9/10
86/86 [==============================] - 0s 1ms/step - loss: 0.4786 - accuracy: 0.7710
Epoch 10/10
43/43 [==============================] - 0s 746us/step


In [97]:
pred = np.round(pred)
accuracy_score(pred,yt)
confusion_matrix(pred,yt)
accuracy_score(pred,yt)

0.7546468401486989

In [98]:
true , false = data.groupby('Exited')
org_data = pd.concat([true[1],false[1]])
x= org_data.drop('Exited',axis=1)
y = org_data.Exited

In [99]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(sampling_strategy = 'minority')
x,y = smote.fit_resample(x,y)


In [100]:
x,xt,y,yt = train_test_split(x,y,test_size = .33)
model = tf.keras.Sequential()
model.add(keras.layers.Flatten(input_shape=(13,)))
model.add (keras.layers.Dense(1000,activation = 'relu'))
model.add (keras.layers.Dense(100,activation = 'relu'))
model.add (keras.layers.Dense(20,activation = 'relu'))
model.add(keras.layers.Dense(1,activation = 'sigmoid'))
model.compile(optimizer = 'Adam', loss= 'binary_crossentropy',metrics = 'accuracy')
model.fit(x,y,epochs = 250)
pred = model.predict(xt)

Epoch 1/250
334/334 [==============================] - 1s 2ms/step - loss: 0.5640 - accuracy: 0.7074
Epoch 2/250
334/334 [==============================] - 1s 2ms/step - loss: 0.4874 - accuracy: 0.7606
Epoch 3/250
334/334 [==============================] - 1s 2ms/step - loss: 0.4724 - accuracy: 0.7615
Epoch 4/250
334/334 [==============================] - 1s 2ms/step - loss: 0.4600 - accuracy: 0.7746
Epoch 5/250
334/334 [==============================] - 1s 2ms/step - loss: 0.4478 - accuracy: 0.7797
Epoch 6/250
334/334 [==============================] - 1s 2ms/step - loss: 0.4429 - accuracy: 0.7849
Epoch 7/250
334/334 [==============================] - 1s 2ms/step - loss: 0.4380 - accuracy: 0.7901
Epoch 8/250
334/334 [==============================] - 1s 2ms/step - loss: 0.4331 - accuracy: 0.7928
Epoch 9/250
334/334 [==============================] - 1s 2ms/step - loss: 0.4304 - accuracy: 0.7932
Epoch 10/250
334/334 [==============================] - 1s 2ms/step - loss: 0.4237 - accura

In [92]:
pred = np.round(pred)
accuracy_score(pred,yt)
confusion_matrix(pred,yt)
# accuracy_score(pred,yt)
from sklearn.metrics import classification_report
print(classification_report(pred,yt))


              precision    recall  f1-score   support

         0.0       0.88      0.75      0.81      2073
         1.0       0.70      0.85      0.77      1449

    accuracy                           0.79      3522
   macro avg       0.79      0.80      0.79      3522
weighted avg       0.81      0.79      0.79      3522



In [101]:
pred = np.round(pred)
accuracy_score(pred,yt)
confusion_matrix(pred,yt)
# accuracy_score(pred,yt)
from sklearn.metrics import classification_report
print(classification_report(pred,yt))


              precision    recall  f1-score   support

         0.0       0.84      0.91      0.88      2410
         1.0       0.92      0.86      0.89      2846

    accuracy                           0.88      5256
   macro avg       0.88      0.88      0.88      5256
weighted avg       0.88      0.88      0.88      5256

